export default {
  date: 'Date',
  vs: 'Text',
  duration: 'Text',

  coachhome: 'Text',
  concededhome: 'Boolean',
  idracehome: 'Text',
  logohome: 'Text',
  teamhome: 'Text',
  scorehome: 'Text',
  scoreaway: 'Text',
  teamaway: 'Text',
  logoaway: 'Text',
  idraceaway: 'Text',
  coachaway: 'Text',
  concededaway: 'Boolean',
  winhome: 'Boolean',
  winaway: 'Boolean',
  drawhome: 'Boolean',
  drawaway: 'Boolean',
  losshome: 'Boolean',
  lossaway: 'Boolean',
  tvdiffhome: 'Integer',
  tvdiffaway: 'Integer',
  concedereceivedhome: 'Boolean',
  concedereceivedaway: 'Boolean',
  valuehome: 'Integer',
  valueaway: 'Integer',
  cashspentinducementshome: 'Integer',
  cashspentinducementsaway: 'Integer',
  inflictedkohome: 'Integer',
  inflictedkoaway: 'Integer',
  sustainedkohome: 'Integer',
  sustainedkoaway: 'Integer',
  inflictedcasualtieshome: 'Integer',
  inflictedcasualtiesaway: 'Integer',
  sustainedcasualtieshome: 'Integer',
  sustainedcasualtiesaway: 'Integer',
  inflicteddeadhome: 'Integer',
  inflicteddeadaway: 'Integer',
  sustaineddeadhome: 'Integer',
  sustaineddeadaway: 'Integer',
  inflictedpushoutshome: 'Integer',
  inflictedpushoutsaway: 'Integer',

  createdDate: 'DateTime',
}
